# Generated by Django 2.1 on 2018-09-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_addr', models.GenericIPAddressField(unique=True)),
                ('port', models.PositiveSmallIntegerField(default=22)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
