# Generated by Django 2.1 on 2018-09-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('collection', models.CharField(max_length=125)),
                ('name', models.CharField(default=None, max_length=255)),
                ('timestamp', models.DateField(auto_now=True)),
                ('record', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SumNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='sumnum',
            name='typec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counter.Types'),
        ),
        migrations.AddField(
            model_name='counter',
            name='typec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counter.Types'),
        ),
    ]
